# Generated by Django 4.1.5 on 2023-03-07 04:16

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('home', '0002_subscriber_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='status',
            field=models.CharField(default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
