# Generated by Django 4.1.5 on 2023-03-07 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_subscriber_status_alter_blog_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='status',
            field=models.CharField(choices=[('1', 'unverified'), ('2', 'verified')], default='1', max_length=1),
        ),
    ]
