# Generated by Django 4.1.5 on 2023-03-26 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_blog_likes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriber',
            unique_together={('user', 'email')},
        ),
    ]
